name: Keep Render App Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  # This line allows you to manually trigger the workflow for testing
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        # Using curl to send a GET request to your app
        run: curl -X GET https://transit-schedule.onrender.com/health
